#------------------------------------------------
# Global Constants
#------------------------------------------------

#JSON key constants
JSONKEYVOLUMECTRL = 'VolumeCtrl'
JSONKEYBASSCTRL = 'BassCtrl'
JSONKEYMIDDLECTRL = 'MiddleCtrl'
JSONKEYTREBBLECTRL = 'TrebbleCtrl'
JSONKEYSELECTCTRL = 'SelectCtrl'
JSONKEYFRONTDOORCTRL = 'FrontDoorCtrl'
JSONKEYPREAMPPOWERCTRL = 'PreampPowerCtrl'
JSONKEYLINEOUTPUTCTRL = 'LineOutputCtrl'
JSONKEYVOLUMEFB = 'VolumeFB'
JSONKEYBASSFB = 'BassFB'
JSONKEYMIDDLEFB = 'MiddleFB'
JSONKEYTREBBLEFB = 'TrebbleFB'
JSONKEYSELECTFB = 'SelectFB'
JSONKEYFRONTDOORFB = 'FrontDoorFB'
JSONKEYPREAMPPOWERFB = 'PreampPowerFB'
JSONKEYLINEOUTPUTFB = 'LineOutputFB'

#Socketio constants
SOCKETIOPREAMPCTRL = 'preampcontrol'
SOCKETIOPOWERCTRL = 'powercontrol'
SOCKETIOPREAMPFB = 'preampfeedback'
SOCKETIOPOWERFB = 'powerfeedback'

#PCA9865 driver constants
I2CPCA9865ADDRESS = 0x40
I2CPCA9865MODE1REG = 0x00
I2CPCA9865MODE2REG = 0x01
I2CPCA9865PUSHPULL = 0x04
I2CPCA9865INVERTER = 0x10
I2CPCA9865AION = 0x20
I2CPCA9865SLEEPON = 0x10
I2CPCA9865SLEEPOFF = 0xEF
I2CPCA9865MAXCH = 15
I2CPCA9865MINCH = 0
I2CPCA9865PRESCALREG = 0xFE
I2CPCA9865PRESCAL50HZ = 0x79

#MCP23S17 driver constants
SPIMCP23S17ADRESS = 0x40
SPIMCP23S17GPIOAREG = 0x12
SPIMCP23S17IODIRA = 0x00
SPIMCP23S17IODIRB = 0x01
SPIMCP23S17CLOCK = 7629

#Servo constants
SERVOMAXANGLE = 95
SERVOMINANGLE = -95
SERVOREGWIDTH = 4
SERVOREGBASE = 6
PWMOFFSET = 161.5
PWMGAIN = 1.116666666

#Preamp Front Door constants
FRONTDOORMOTOR1 = 0
FRONTDOORMOTOR2 = 1
FRONTDOORCLOSEPOS = -91
FRONTDOOROPENPOS = 91
FRONDDOORPOSSTEP = 10
FRONTDOORSTEPDELAY = 0.03
FRONTDOORSETTLEDELAY = 0.2
KNOBSLIDEMOTOR1 = 2
KNOBSLIDEMOTOR2 = 3
KNOBSLEDECLOSEPOS = -91
KNOBSLIDEOPENPOS = 91
KNOBSLIDEPOSSTEP = 10

#Audio Controls constants
CONTROLVOLUMECH = 4
CONTROLBASSCH = 5
CONTROLMIDDLECH =6
CONTROLTREBBLECH = 7
CONTROLSMAX = 100
CONTROLSMIN = -100
CONTROLSZERO = 0
CONTROLOFFSET = -90
CONTROLGAIN1 = 1.8
CONTROLGAIN2 = 0.9

#LED controls constants
LEDBLINKPERIOD = 6
LEDMAINPOWER = 8
LEDSTANDBY = 9
LEDMEDIAPLAYER = 10
LEDENETRADIO = 11
LEDDVDPLAYER = 12
LEDAUXILIARY = 13

#Relay control constants
RELAYPREAMPPOWER = 0x08
RELAYPREAMPLINEOUT = 0x10
RELAYPREAMPNOCHANNEL = 0xF8
RELAYPREAMPINTERNALCHANNEL = 0x01
RELAYPREAMPDVDCHANNEL = 0x02
RELAYPREAMPAUXCHANNEL = 0x04

#General constants
HEARTBEAT = 50
PWMONDELAY = 4
THREADTIMEDELAY = 0.1
LARGETHREADTIMEDELAY = 0.5
MAXAUDIOINPUTS = 4
HTMLPAGELOCATION = '/var/www/html/index.html'
